[Distribution]
Distribution=arch

[Config]
Profiles=nvidia,desktop,kde,flatpak,containers

[Content]
Packages=
        starship
        ttf-firacode-nerd
        ttf-nerd-fonts-symbols
        tmux
        btop
        rsync
        rclone
