[Distribution]
Distribution=arch

[Config]
Profiles=desktop,kde,nvidia,flatpak,containers

[Content]
Packages=
        starship
        ttf-firacode-nerd
        ttf-nerd-fonts-symbols
        tmux
        htop
        rsync
        rclone
