# SPDX-License-Identifier: LGPL-2.1-or-later

# Requires desktop profile.

[Content]
Packages=
        bluedevil
        breeze-gtk
        dolphin
        flatpak-kcm
        kde-gtk-config
        kdeconnect
        kdegraphics-thumbnailers
        kdeplasma-addons
        kgamma
        kinfocenter
        konsole
        kscreen
        ksshaskpass
        kwallet-pam
        kwrited
        ocean-sound-theme
        plasma-desktop
        plasma-disks
        plasma-keyboard
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-thunderbolt
        plasma-welcome
        plasma-workspace-wallpapers
        powerdevil
        sddm
        sddm-kcm
        spectacle
        xdg-desktop-portal-kde
