# SPDX-License-Identifier: LGPL-2.1-or-later

# Requires desktop profile.

[Content]
Packages=
        sddm
        sddm-kcm
        dolphin
        konsole
        kinfocenter
        kdeconnect
        spectacle
        xdg-desktop-portal-kde
        xdg-desktop-portal-gtk
