# SPDX-License-Identifier: LGPL-2.1-or-later

# Requires desktop profile.

[Content]
Packages=
        bluedevil
        breeze
        breeze-gtk
        discover
        dolphin
        drkonqi
        flatpak-kcm
        kactivitymanagerd
        kde-cli-tools
        kde-gtk-config
        kdeconnect
        kdecoration
        kdeplasma-addons
        kglobalacceld
        kinfocenter
        knighttime
        konsole
        kpipewire
        krdp
        kscreen
        kscreenlocker
        ksshaskpass
        ksystemstats
        kwallet-pam
        kwayland
        kwin
        kwrited
        layer-shell-qt
        libkscreen
        libksysguard
        libplasma
        milou
        ocean-sound-theme
        plasma-activities
        plasma-activities-stats
        plasma-browser-integration
        plasma-desktop
        plasma-disks
        plasma-integration
        plasma-keyboard
        plasma-login-manager
        plasma-nm
        plasma-pa
        plasma-systemmonitor
        plasma-thunderbolt
        plasma-welcome
        plasma-workspace
        plasma-workspace-wallpapers
        polkit-kde-agent
        powerdevil
        print-manager
        sddm
        sddm-kcm
        spectacle
        systemsettings
        xdg-desktop-portal-gtk
        xdg-desktop-portal-kde
