# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
InitrdPackages=
        plymouth
        breeze-plymouth

Packages=
        plasma-keyboard
        breeze-plymouth
        discover
        drkonqi
        print-manager
        dolphin-plugins
        ffmpegthumbs
