# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
InitrdPackages=
        plymouth
        breeze-plymouth

Packages=
        plasma-keyboard
        discover
        colord-kde
        drkonqi
        kde-inotify-survey
        breeze-plymouth
        dolphin-plugins
        print-manager
        ffmpegthumbs
        sweeper
