# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
InitrdPackages=
        plymouth
        breeze-plymouth

Packages=
        plasma-meta
        kde-inotify-survey
        kwayland-integration
        plasma5-integration
        plymouth
        breeze-plymouth
        discover
        colord-kde
        dolphin-plugins
        kdegraphics-thumbnailers
        ffmpegthumbs
        sweeper
