# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp

InitrdPackages=
        plymouth
        breeze-plymouth

Packages=
        adobe-source-code-pro-fonts
        linux-firmware
        intel-media-driver
        mesa
        modemmanager
        networkmanager
        noto-fonts
        plymouth
        breeze-plymouth
        pipewire-pulse
        sof-firmware
        vulkan-intel
        vulkan-radeon
        vulkan-mesa-layers
        wpa_supplicant
