# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp

Packages=
        adobe-source-code-pro-fonts
        linux-firmware
        linux-zen
        linux-zen-headers
        scx-scheds
        intel-media-driver
        mesa
        modemmanager
        networkmanager
        geoclue
        noto-fonts
        pipewire
        pipewire-pulse
        sof-firmware
        vulkan-intel
        vulkan-radeon
        vulkan-mesa-layers
        vulkan-tools
        wpa_supplicant
